# Generated by Django 3.1.1 on 2020-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_tag_taginblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='sample_text',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
