# Generated by Django 3.1.1 on 2020-12-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_sample_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='title_img',
        ),
    ]
