# Generated by Django 3.1.1 on 2020-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blogs_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='sample_text',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
